# Generated by Django 4.0.5 on 2022-06-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms_base.basemodel')),
                ('header_image_src', models.URLField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=100)),
            ],
            bases=('cms_base.basemodel',),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms_base.basemodel')),
                ('url', models.URLField(max_length=300)),
                ('short_name', models.CharField(max_length=50)),
                ('resource_type', models.CharField(choices=[('A', 'Article'), ('V', 'Video')], max_length=1)),
                ('owned_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='cms_base.article')),
            ],
            bases=('cms_base.basemodel',),
        ),
    ]
