# Generated by Django 4.0.5 on 2022-06-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_base', '0004_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
    ]
